### ISSUE TITLE
Cannot load selector from vault

### ISSUE THREAD

**Issue by jbaiter** [IIIF-Commons/parser#15]
When loading the manifest at https://gist.githubusercontent.com/jbaiter/199b2b31e0aeaf9811a3baec22579853/raw/cf1e3c067fabbf0ddd79bb291786f7b9ff5a6ef9/start-selector.manifest.json with vault, the selector in the manifest's `start` property fails to load from the vault:

```javascript
import { globalVault } from '@iiif/vault';

const vault = globalVault();
vault.loadManifest(
  'https://gist.githubusercontent.com/jbaiter/199b2b31e0aeaf9811a3baec22579853/raw/cf1e3c067fabbf0ddd79bb291786f7b9ff5a6ef9/start-selector.manifest.json'
).then(manifest => {
  const startRef = manifest.start;  // { "id": "http://example.org/selector/1", "type": "SpecificResource" }
  const selector = vault.get(startRef); // null
})
```

Sandbox: https://codesandbox.io/s/beautiful-noyce-jvk4sq?file=/src/index.js

**Comment by stephenwf** [comment]
`vault.get()` now supports "SpecificResource"
