### ISSUE TITLE
Converting improperly formatted Language of Property Values

### ISSUE THREAD

**Issue by JackNolanDev** [IIIF-Commons/parser#33]
I was attempting to convert some iiif-manifests from v2 to v3 from the Art Institute of Chicago, and was running into issues where the `description` -> `summary` values where getting lost. It looks like their API doesn't quite follow the spec - they are using `"value"` and `"language"` for key values within Language blocks (https://iiif.io/api/presentation/2.1/#language-of-property-values) instead of `"@value"` and `"@language"`.

Example: https://api.artic.edu/api/v1/artworks/27992/manifest.json

I was wondering this parser could handle this case.
I only peeked through the code in this repo, but it seems like it should be a relatively simple fix around here:
https://github.com/IIIF-Commons/parser/blob/276de3ce05df979e7c9ae401576341a9c2d5e31d/src/presentation-2/upgrader.ts#L15-L48

**Comment by stephenwf** [comment]
Thanks @JackNolanDev there is a fix up at #34 

You can test the package locally using the instructions heres:
https://ci.codesandbox.io/status/IIIF-Commons/parser/pr/34/builds/463154

It will be in the next patch release 👍

**Comment by JackNolanDev** [comment]
I have verified the changes are working! Thank you so much!
