### ISSUE TITLE
Wrong casing in README

### ISSUE THREAD

**Issue by cmahnke** [IIIF-Commons/parser#45]
I tried to use `Traverse`, as documented in the [README](https://github.com/IIIF-Commons/parser/blob/main/README.md?plain=1#L47), like this:
```
  const extractManifests = new Traverse({
    Manifest: [(manifest) => {
      console.log(manifest.id);
      manifests.push(manifest.id);
    }],
  });
```
It turns out the the (quite sparse) documentation is wrong: Notice the upper case of the first letter of `Manifest`.

If one has a look at the [test](https://github.com/IIIF-Commons/parser/blob/main/__tests__/presentation-3-parser/iiif-traverse.test.ts) it's obvious that the type is expected in lower case (that would be `manifest`). After changing to lower case the example is applicable.

Either the documentation needs to be updated or the code changed to accept `ucfirst` type names. While the later is 
 the more consistent solution, it would certainly be a breaking change...

**Comment by stephenwf** [comment]
I've fixed the documentation, but I think the ucfirst names feels more natural. I don't think it would be too difficult to add support for both.

Are there any areas of the documentation you'd like prioritised?

**Comment by stephenwf** [comment]
Hmm, I think those functions would be used at a higher level. 

The `@iiif/parser` is used by libraries like: `@iiif/helpers` to provide similar functionality.

https://github.com/iiif-commons/iiif-helpers

There is some [documentation here](https://iiif-commons.netlify.app/docs/vault-helpers/content-state) (note: package name has changed)

Here's a [quick sandbox](https://codesandbox.io/p/sandbox/kgy5gs?welcomeVSCode=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0p9lbr400063b6n2xof7v61%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0p9lbr400023b6nmdrfwmgo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0p9lbr400033b6n22ummuf0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0p9lbr400053b6nbi9ylsez%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0p9lbr400023b6nmdrfwmgo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0p9lbr400013b6nzos9megs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0p9lbr400023b6nmdrfwmgo%2522%252C%2522activeTabId%2522%253A%2522cm0p9lbr400013b6nzos9megs%2522%257D%252C%2522cm0p9lbr400053b6nbi9ylsez%2522%253A%257B%2522id%2522%253A%2522cm0p9lbr400053b6nbi9ylsez%2522%252C%2522activeTabId%2522%253A%2522cm0p9nlwi001o3b6m851eyrpb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0p9lbr400043b6n6w5d6aut%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522cm0p9lfo8002i3b6no56os82t%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm0p9nlwi001o3b6m851eyrpb%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0p9lbr400033b6n22ummuf0%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0p9lbr400033b6n22ummuf0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) of a few things that Helpers provides over the Parser.

**Comment by cmahnke** [comment]
Ok, thanks. I'll have a look.
Using `Traverse` doesn't know about something like `ImageService2` anyways, so the second proposed example won't be possible anyways.
